on:
  pull_request:
    branches:
      - '*'
  push:
    branches:
      - '*'

env:
  PYTHON_VERSION: '3.10

name: Test
jobs:
  unit-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ env.PYTHON_VERSION }}
          cache: "pip"

      - name: Install dependencies
        run: | 
          sudo apt-get update
          sudo apt-get install python3-pip
          python3 -m venv env
          source env/bin/activate
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
          pip install --upgrade pip

      - name: Run unit-tests
        run: |
          source env/bin/activate
          pytest --cov
          pytest --cov --cov-report=html